# Using version 3 to provide play-with-docker badge
# You can change to version 2 without breaking.
#version: '2'
version: '3'
services:
  app:
    # Uncomment the following section to build the image yourself:
    build:
      context: .
      dockerfile: alpine/Dockerfile
      args:
        - "VERSION=master"
        - "HACKMD_REPOSITORY=https://github.com/getstation/hackmd.git"
    environment:
      # DB_URL is formatted like: <databasetype>://<username>:<password>@<hostname>/<database>
      # Other examples are: 
      # - mysql://database:3306/database
      # - sqlite:///data/sqlite.db (NOT RECOMMENDED)
      # - For details see the official sequelize docs: http://docs.sequelizejs.com/en/v3/
      - HMD_DB_URL=postgres://hackmd:hackmdpass@hackmdPostgres:5432/hackmd
    ports:
      # Ports that are published to the outside.
      # The latter port is the port inside the container. It should always stay on 3000
      # If you only specify a port it'll published on all interfaces. If you want to use a 
      # local reverse proxy, you may want to listen on 127.0.0.1.
      # Example:
      # - "127.0.0.1:3000:3000"
      - "3000:3000"
    networks:
      backend:
    restart: always

# Define networks to allow best isolation
networks:
  # Internal network for communication with Postgres
  backend:

# Define named volumes so data stays in place
volumes:
  # Volume for Postgres database
  database:
